<?php

class FooterView extends View
{
    public function getHTML(): string
    {
        return "<footer>
                <div>Matyniov's Corp. | Most right reserved, i think? I mean, the website is my idea, the code was written by me, the contents of the articles are 95% generated by chatGPT and quizes are bright examples of my imagination... I think thats not that big of a deal, right?</div>
            </footer>";
    }
}
